version: '3.0'
services:
  mautic:
    image: mautic/mautic
    container_name: mautic
    restart: always
    ports:
      - "80:80"
    env_file:
      - mautic.env
    volumes:
      - mautic-data:/var/www/html
    networks:
      - mautic-net
    depends_on:
      - db-mautic
      - wordpress
  db-mautic:
    image: mysql:5.6
    container_name: db-mautic
    restart: always
    volumes:
      - db-mautic-data:/var/lib/mysql
    env_file:
      - mautic.env
    networks:
      - mautic-net

  magento:
    image: alexcheng/magento2
    container_name: magento
    restart: always
    ports:
      - "81:80"
    env_file:
      - magento.env
    volumes:
      - magento-data:/var/www/html
    networks:
      - magento-net
    depends_on:
      - db-magento
  db-magento:
    image: mysql:5.6
    container_name: db-magento
    restart: always
    volumes:
      - db-magento-data:/var/lib/mysql
    env_file:
      - magento.env
    networks:
      - magento-net     

  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    ports:
      - 82:80
    env_file:
      - wordpress.env
    volumes:
      - wordpress-data:/var/www/html
    networks: 
      - wordpress-net
    depends_on:
      - db-wordpress
  db-wordpress:
    image: mysql:5.7
    container_name: db-wordpress
    restart: always
    volumes:
      - db-wordpress-data:/var/lib/mysql
    env_file:
      - wordpress.env
    networks:
      - wordpress-net  


volumes:
  db-wordpress-data:
  db-magento-data:
  db-mautic-data:
  wordpress-data:
  magento-data:
  mautic-data:

networks:
  wordpress-net:
  magento-net:
  mautic-net:
